Repository aws-controllers-k8s/iam-controller, pull requests merged in 2021-12, with the labels that each got.

#3 add Role resource
  NOTICE
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/role.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/controller/deployment.yaml
  config/crd/bases/iam.services.k8s.aws_roles.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  go.mod
  go.sum
  helm/crds/iam.services.k8s.aws_roles.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/deployment.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  helm/values.yaml
  pkg/resource/role/delta.go
  pkg/resource/role/descriptor.go
  pkg/resource/role/identifiers.go
  pkg/resource/role/manager.go
  pkg/resource/role/manager_factory.go
  pkg/resource/role/resource.go
  pkg/resource/role/sdk.go
  test/e2e/.gitignore
  test/e2e/__init__.py
  test/e2e/bootstrap_resources.py
  test/e2e/common/__init__.py
  test/e2e/common/types.py
  test/e2e/conftest.py
  test/e2e/replacement_values.py
  test/e2e/requirements.txt
  test/e2e/resources/role_simple.yaml
  test/e2e/role.py
  test/e2e/service_bootstrap.py
  test/e2e/service_cleanup.py
  test/e2e/tests/__init__.py
  test/e2e/tests/test_role.py
Labels: approved

#4 Ensure ResourceSynced condition set
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  config/iam/recommended-inline-policy
  generator.yaml
  helm/templates/deployment.yaml
  helm/values.yaml
  pkg/resource/role/sdk.go
  templates/hooks/role/sdk_create_post_set_output.go.tpl
  templates/hooks/role/sdk_update_post_set_output.go.tpl
  test/e2e/requirements.txt
  test/e2e/tests/test_role.py
Labels: approved, lgtm

#5 release artifacts for v0.0.1
  helm/Chart.yaml
  helm/values.yaml
Labels: approved, lgtm

#6 add Policy resource
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/policy.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/iam.services.k8s.aws_policies.yaml
  config/crd/kustomization.yaml
  config/iam/recommended-inline-policy
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/iam.services.k8s.aws_policies.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  pkg/resource/policy/delta.go
  pkg/resource/policy/descriptor.go
  pkg/resource/policy/identifiers.go
  pkg/resource/policy/manager.go
  pkg/resource/policy/manager_factory.go
  pkg/resource/policy/resource.go
  pkg/resource/policy/sdk.go
  templates/hooks/policy/sdk_create_post_set_output.go.tpl
  test/e2e/common/types.py
  test/e2e/policy.py
  test/e2e/resources/policy_simple.yaml
  test/e2e/tests/test_policy.py
  test/e2e/tests/test_role.py
Labels: approved, lgtm

#7 adding in missing olmconfig file
  olm/olmconfig.yaml
Labels: approved, lgtm, ok-to-test

#9 release artifacts for v0.0.2
  helm/Chart.yaml
  helm/crds/iam.services.k8s.aws_roles.yaml
  helm/values.yaml
Labels: approved, lgtm
