Repository aws-controllers-k8s/iam-controller, pull requests merged in 2023-04, with the labels that each got.

#74 feat: sync assume role policy document
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/role/hooks.go
  pkg/resource/role/sdk.go
  templates/hooks/role/sdk_update_pre_build_request.go.tpl
  test/e2e/role.py
  test/e2e/tests/test_role.py
Labels: approved, lgtm, ok-to-test

#75 Release artifact for release `v1.2.0`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved

#76 fix: update recommended inline policy to include `iam:UpdateAssumeRolePolicy`
  config/iam/recommended-inline-policy
Labels: approved, lgtm, needs-ok-to-test
